import localFont from "next/font/local"
import { Plus_Jakarta_Sans } from "next/font/google"

import Providers from "./Providers";
import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const trajan = localFont({
  src: [
    {
      path: './font/TrajanPro-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './font/TrajanPro-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: "--font-trajan"
})

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jakarta"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${trajan.variable} ${plusJakartaSans.className} text-dark-primary antialiased`}
      >
        <Providers>
          <div className="flex flex-col w-full justify-between min-h-screen">
            <div>
              <Navbar />
              {children}
            </div>
            <div className="w-full place-items-end">
              <Footer />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
